FROM node:alpine
LABEL maintainer="jose.duran@duransoftware.es"
LABEL description="Mongo CRUD general api"
LABEL version="1.0.0"

RUN mkdir /app
RUN mkdir /app/swagger
RUN mkdir /app/node_modules

WORKDIR .

ADD ./docker/DSMongoApi.js ./app/ 
	ADD ./docker/swagger/ ./app/swagger/
	ADD node_modules/ ./app/node_modules/


WORKDIR ./app

RUN ls -la /app/*




EXPOSE 51234
CMD ["node", "DSMongoApi"]
